name: Deploy ADF Pipelines

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/setup-azurecli@v1

    - name: Install jq
      run: sudo apt-get install jq

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Read JSON files and Deploy ADF Pipelines
      run: |
        # Read the content of pipeline1.json and pipeline2.json
        pipeline1=$(cat ./pipelines/pipeline1.json)
        pipeline2=$(cat ./pipelines/pipeline2.json)
        
        # Construct the JSON object with the pipeline contents
        pipelines=$(jq -n \
          --arg pipeline1 "$pipeline1" \
          --arg pipeline2 "$pipeline2" \
          '[
            {
              "name": "Pipeline1",
              "definition": $pipeline1 | fromjson
            },
            {
              "name": "Pipeline2",
              "definition": $pipeline2 | fromjson
            }
          ]')

        # Deploy using Bicep (or ARM template)
        az deployment sub create \
          --location eastus \
          --template-file ./adf/adfpipeline.bicep \
          --parameters dataFactoryName=myDataFactory \
          --parameters pipelines="$pipelines"
